### ISSUE TITLE
Hard Reset crashes if more than one browser windows are open.

### ISSUE THREAD

**Issue by miagg** [yan-foto/electron-reload#29] opened 2017-03-08 01:17 UTC
To reproduce:

On main process I create two browser windows.
If I hard reset by changing main.js, A second process is spawned but the first one crashes throwing the following error: 

![screen shot 2017-03-08 at 3 03 08 am](https://cloud.githubusercontent.com/assets/6439071/23685262/d0f8e2fc-03ab-11e7-8f3a-6709bf01fb9e.png)

Here is how I require electron-reload:

```
const reload = require('electron-reload')(__dirname, {
    ignored: /node_modules|dist|build|[\/\\]\./,
    electron: 'node_modules/.bin/electron'
  });
```

I managed to temporary solve the problem by adding `main.js` to the ignored list.
Then, hard reset works fine.
So I guess, maybe It tries to refresh the windows after the have been destroyed?

**Comment by yan-foto** [comment] 2017-03-08 08:00
[This line](https://github.com/yan-foto/electron-reload/blob/master/main.js#L29) is exactly there to avoid reloading after browser window is closed. However, the question is which event handler ([`onChange`](https://github.com/yan-foto/electron-reload/blob/master/main.js#L17) or [`watch`](https://github.com/yan-foto/electron-reload/blob/master/main.js#L43)) is executed first. Could you please check that out? (I'm really short of time and it might take a while for me to fix it)

In any case, I think you are right in saying that `main.js` should be excluded from watched glob **if** hard reset is enable.

**Comment by miagg** [comment] 2017-03-08 10:56
I logged all the event handlers on electron-reload main.js. 
Here is the output:
```
window created
window created
main.js watch
window closed
window closed
onChange // This shouldn't be called since windows are destroyed.
window created
window created
```
You need to validate that `browserWindows` has at least one element before you call `forEach`.
That's how I solved it.
Although it would be better if you manually include main.js to the ignored list. Seems better.

**Comment by miagg** [comment] 2017-03-08 11:48
That was an accidental propose to fix the problem.
Unfortunately it wasn't the case, since forEach does nothing on empty arrays.
So the bw instances remain in the array after the windows are closed, which cause this line 
`bw.webContents.reloadIgnoringCache();`
to throw an error, since bw does not exist.

**Comment by HeilTec** [comment] 2017-03-08 21:07
I concur.
I had the same problem and fixed it by a call to `watcher.unwatch(mainFile);` just before the hard reset watch is initiated in `chokidar.watch(mainFile).on('change', () => {`

Changes to the `mainFile` should not cause pages to reload.
I think this makes sense, since any reloaded pages would be closed by the hard reset. 
Then I went looking for an electron-auto-reload-pages on app-start ... perhaps I should make such a thing.

**Comment by yan-foto** [comment] 2017-03-09 08:51
@miagg `onChange` is called regardless of browser windows and this behavior is fine. As you and @HeilTec confirmed, `main.js` should be excluded but as I mentioned previously **only** if hard-reset is active.

**Comment by quintonn** [comment] 2017-05-09 06:13
How do I add main.js to the ignore list?
I'm having this issue too.

**Closed** 2017-05-18 11:44 UTC
Labels: bug
