### ISSUE TITLE
please add typescript types 

### ISSUE THREAD

**Issue by kerolloz** [yan-foto/electron-reload#60] opened 2019-07-18 12:34 UTC
## What is the problem

![image](https://user-images.githubusercontent.com/36763164/61457762-51c47300-a969-11e9-883f-73c57aec80b0.png)

```
Could not find a declaration file for module 'electron-reload'. '/home/koko/hodhod-electron/node_modules/electron-reload/main.js' implicitly has an 'any' type.
  Try `npm install @types/electron-reload` if it exists or add a new declaration (.d.ts) file containing `declare module 'electron-reload';`ts(7016)
```

## How to reproduce

install and import electron-reload

**Comment by yan-foto** [comment] 2019-08-03 13:13
Duplicate of #22

**Comment by yan-foto** [comment] 2019-08-03 13:14
@kerolloz please see #22 and submit a pull request if you are experienced enough with TS.

**Closed by yan-foto** 2019-08-03 13:13 UTC
