### ISSUE TITLE
`vibrancy` lost after reload

### ISSUE THREAD

**Issue by Bartozzz** [yan-foto/electron-reload#23] opened 2017-01-02 22:26 UTC
When making changes, the `vibrancy` is lost after each consecutive reload and thus the background in set to white. I am talking about the new feature in Electron making the `BrowserWindow` transparent and stuff behind it blurred. Example:

```javascript
new BrowserWindow( {
    vibrancy : "dark"
} );
```

... any ideas how to fix this?

**Comment by yan-foto** [comment] 2017-01-03 10:05
That is indeed strange 🤔...

Is this happening by hard or soft reset or both?

**Comment by Bartozzz** [comment] 2017-01-03 12:28
It is happening on both hard and soft resets.

**Comment by yan-foto** [comment] 2017-01-03 13:42
That is really interesting! At least for hard reset I would expect a correct behavior, since the whole process is restarted and not just the browser windows. It may be caused by the fact that a new process is spawned before the old one is killed. But this is just a wild speculation...

Have you looked at current issues of electron itself?

**Comment by Bartozzz** [comment] 2017-01-03 17:25
Correct. It's seems that this is an issue in Electron: https://github.com/electron/electron/issues/8310 Well, I hope they will resolve this as soon as possible. It's hard to make user interfaces with vibrancy lost after each change.

**Comment by yan-foto** [comment] 2017-01-04 06:38
Alright! I'm gonna close this issue then.

**Closed by yan-foto** 2017-01-04 06:38 UTC
Labels: invalid, wontfix
